/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Compression: () => import('#controllers/compression_controller'),
  Stats: () => import('#controllers/stats_controller'),
}
