/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CompressionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'kind', 'mode', 'originalSize', 'outputSize'] as const
  $columns = CompressionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare mode: string
  @column()
  declare originalSize: bigint | number
  @column()
  declare outputSize: bigint | number
}

export class VisitorSchema extends BaseModel {
  static $columns = ['createdAt', 'id'] as const
  $columns = VisitorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
}
